#
# This module is provided as SLICERLIBCURL_USE_FILE by SLICERLIBCURLConfig.cmake.  
# It can be INCLUDEd in a project to load the needed compiler and linker
# settings to use SLICERLIBCURL:
#   FIND_PACKAGE(SLICERLIBCURL REQUIRED)
#   INCLUDE(${SLICERLIBCURL_USE_FILE})
#

IF(NOT SLICERLIBCURL_USE_FILE_INCLUDED)
  SET(SLICERLIBCURL_USE_FILE_INCLUDED 1)

  # Load the compiler settings used for SLICERLIBCURL.
  #IF(SLICERLIBCURL_BUILD_SETTINGS_FILE)
    #INCLUDE(${CMAKE_ROOT}/Modules/CMakeImportBuildSettings.cmake)
    #CMAKE_IMPORT_BUILD_SETTINGS(${SLICERLIBCURL_BUILD_SETTINGS_FILE})
  #ENDIF(SLICERLIBCURL_BUILD_SETTINGS_FILE)

  # Add compiler flags needed to use SLICERLIBCURL.
  #SET(CMAKE_C_FLAGS 
    #"${CMAKE_C_FLAGS} ${SLICERLIBCURL_REQUIRED_C_FLAGS}")
  #SET(CMAKE_CXX_FLAGS 
    #"${CMAKE_CXX_FLAGS} ${SLICERLIBCURL_REQUIRED_CXX_FLAGS}")
  #SET(CMAKE_EXE_LINKER_FLAGS 
    #"${CMAKE_EXE_LINKER_FLAGS} ${SLICERLIBCURL_REQUIRED_EXE_LINKER_FLAGS}")
  #SET(CMAKE_SHARED_LINKER_FLAGS 
    #"${CMAKE_SHARED_LINKER_FLAGS} ${SLICERLIBCURL_REQUIRED_SHARED_LINKER_FLAGS}")
  #SET(CMAKE_MODULE_LINKER_FLAGS 
    #"${CMAKE_MODULE_LINKER_FLAGS} ${SLICERLIBCURL_REQUIRED_MODULE_LINKER_FLAGS}")

  # Add include directories needed to use SLICERLIBCURL.
  INCLUDE_DIRECTORIES(${SLICERLIBCURL_INCLUDE_DIRS})

  # Add link directories needed to use SLICERLIBCURL.
  LINK_DIRECTORIES(${SLICERLIBCURL_LIBRARY_DIRS})

  #ADD_DEFINITIONS(-DHAVE_CONFIG_H)

  # Add cmake module path.
  #SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${SLICERLIBCURL_CMAKE_DIR}")

ENDIF(NOT SLICERLIBCURL_USE_FILE_INCLUDED)
